---
# Petclinic deployment procedure
- hosts: local-env
  become: yes
  become_method: sudo 
  tasks:
   - name: Creating deployment folder structure
     shell: |
       rm -rf /home/{{user}}/petclinic
       mkdir -p /home/{{user}}/petclinic
   - name: Get distribution package from Nexus
     shell: |
       wget http://{{nexusserver}}/repository/maven-releases/org/criticalsoftware/sspa/petclinic/{{appversion}}/petclinic-{{appversion}}.tar.gz -O //home/{{user}}/petclinic/petclinic-{{appversion}}.tar.gz
       chmod +x mkdir -p /home/{{user}}/petclinic/petclinic-{{appversion}}.tar.gz
       tar -xvf /home/{{user}}/petclinic/petclinic-{{appversion}}.tar.gz
   - name: Starting application...
     shell: |
        /home/{{user}}/petclinic/petclinic-{{appversion}}/mvnw spring-boot:run
        /home/{{user}}/petclinic/petclinic-{{appversion}}/client/npm install
        /home/{{user}}/petclinic/petclinic-{{appversion}}/client/PORT=4444 npm start
        

   